#! /usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Slidify', '1.0');

$app->add(new Slidify\Console\Commands\ExportCommand);
$app->add(new Slidify\Console\Commands\Config\MakeCommand);
$app->add(new Slidify\Console\Commands\Config\ViewCommand);
$app->add(new Slidify\Console\Commands\Config\CheckCommand);

$app->run();
